# Generated by Django 5.0.6 on 2024-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='pfp',
            field=models.ImageField(blank=True, default='static/images/pfp.png', null=True, upload_to='pfp'),
        ),
    ]
