# Generated by Django 5.0.6 on 2024-06-03 02:47

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_filemessage_author_remove_filemessage_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_file),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_file),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_file),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_file),
        ),
    ]
